In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[2,3,5,4,8,9,6,10,23],[1,4,2,54,65,34,73,88,76]])
print(b)

[[ 2  3  5  4  8  9  6 10 23]
 [ 1  4  2 54 65 34 73 88 76]]


In [5]:
a.ndim
b.ndim

2

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [10]:
b[0, 1:6:2]

array([3, 4, 9])

In [11]:
# All zero matrix
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#All 1 matrix
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [15]:
#Any number matrix
np.full((3,2),72)

array([[72, 72],
       [72, 72],
       [72, 72]])

In [16]:
#Matrix of shape that has already initialized

np.full_like(b, 72)

array([[72, 72, 72, 72, 72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72, 72, 72, 72, 72]])

In [17]:
#matrix of random numbers

np.random.rand(3,8)

array([[0.66866246, 0.5174921 , 0.18369877, 0.59273609, 0.68390957,
        0.56016216, 0.38591546, 0.59432377],
       [0.04592405, 0.63842095, 0.18664677, 0.25020971, 0.61243283,
        0.4075991 , 0.50316403, 0.14104378],
       [0.50412384, 0.02525892, 0.61330983, 0.97564298, 0.15976986,
        0.1083685 , 0.4630075 , 0.93331843]])

In [20]:
# Random Integer values

np.random.randint(7, size=(3,3))

array([[0, 5, 3],
       [6, 0, 5],
       [5, 0, 1]])

In [21]:
#indentity Matrix

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
output = np.ones((5,5))
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [24]:
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
a = np.array([1,2,3])
b = a.copy()
b[0]= 100
print(a)

[1 2 3]


In [31]:
a+=2
print(a)

[5 6 7]


In [33]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.min(stats)

1

In [35]:
np.max(stats)

6

In [37]:
# Vertical Stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])